### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
### - - - - - - - - - - - - - - - - - - - - L O C A L H O S T - - - - - - - - - - - - - - - - - - -
### - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
###
GET http://0.0.0.0:4888/article/1
Content-Type: application/json

###
GET http://0.0.0.0:4888/articles
Content-Type: application/json

